package LawFirmProject;

import javax.swing.JOptionPane;
//import lawfirmproject.CreatCaseJframe;

public class HireLawyerJframe extends javax.swing.JFrame {


	   LawFirm LawFirm1 = new LawFirm( "Law Firm", "Riyadh" , "2010" ,  "Haneen" , 50 );
	   
	Lawyer NewLawyer;

	    /**
	     * Creates new form HireLawyerJframe
	     */
	    public HireLawyerJframe() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        buttonGroup1 = new javax.swing.ButtonGroup();
	        buttonGroup2 = new javax.swing.ButtonGroup();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jRadioButton1 = new javax.swing.JRadioButton();
	        jRadioButton2 = new javax.swing.JRadioButton();
	        jRadioButton3 = new javax.swing.JRadioButton();
	        jRadioButton4 = new javax.swing.JRadioButton();
	        jRadioButton5 = new javax.swing.JRadioButton();
	        jRadioButton6 = new javax.swing.JRadioButton();
	        jButton1 = new javax.swing.JButton();
	        jTextField1 = new javax.swing.JTextField();
	        jTextField2 = new javax.swing.JTextField();
	        jTextField3 = new javax.swing.JTextField();
	        jTextField4 = new javax.swing.JTextField();
	        jTextField5 = new javax.swing.JTextField();
	        jLabel8 = new javax.swing.JLabel();
	        jTextField6 = new javax.swing.JTextField();
	        jButton2 = new javax.swing.JButton();
	        jLabel9 = new javax.swing.JLabel();
	        jTextField7 = new javax.swing.JTextField();
	        jButton3 = new javax.swing.JButton();
	        jLabel10 = new javax.swing.JLabel();
	        jTextField8 = new javax.swing.JTextField();
	        jButton4 = new javax.swing.JButton();

	        setPreferredSize(new java.awt.Dimension(900, 800));

	        jLabel1.setText("Enter Lawyer’s Name :");

	        jLabel2.setText("Choose Lawyer’s Experience Level : ");

	        jLabel3.setText("Enter Lawyer’s Email Address : ");

	        jLabel4.setText("Enter Lawyer’s Phone Number : ");

	        jLabel5.setText("Choose Lawyer’s License Status :");

	        jLabel6.setText("Enter Lawyer’s Bar Number : ");

	        jLabel7.setText("Enter Lawyer’s University Name : ");

	        buttonGroup1.add(jRadioButton1);
	        jRadioButton1.setText("Junior (J) ");
	        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton1ActionPerformed(evt);
	            }
	        });

	        buttonGroup1.add(jRadioButton2);
	        jRadioButton2.setText("Senior (S)");

	        buttonGroup1.add(jRadioButton3);
	        jRadioButton3.setText("Partner(P)");
	        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton3ActionPerformed(evt);
	            }
	        });

	        buttonGroup2.add(jRadioButton4);
	        jRadioButton4.setText("Active (A) ");
	        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton4ActionPerformed(evt);
	            }
	        });

	        buttonGroup2.add(jRadioButton5);
	        jRadioButton5.setText("Suspended (S) ");

	        buttonGroup2.add(jRadioButton6);
	        jRadioButton6.setText("Revoked (R) ");

	        jButton1.setBackground(new java.awt.Color(204, 204, 204));
	        jButton1.setForeground(new java.awt.Color(0, 0, 0));
	        jButton1.setText("Finish");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jTextField3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField3ActionPerformed(evt);
	            }
	        });

	        jTextField5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField5ActionPerformed(evt);
	            }
	        });

	        jLabel8.setText("Enter The Maximum Number Of Cases That The Lawyer Can Handle :");

	        jTextField6.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField6ActionPerformed(evt);
	            }
	        });

	        jButton2.setBackground(new java.awt.Color(204, 204, 204));
	        jButton2.setForeground(new java.awt.Color(0, 0, 0));
	        jButton2.setText("Save");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });

	        jLabel9.setText("Enter Lawyer’s Years Of Experience : ");

	        jButton3.setBackground(new java.awt.Color(204, 204, 204));
	        jButton3.setForeground(new java.awt.Color(0, 0, 0));
	        jButton3.setText("Save");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton3ActionPerformed(evt);
	            }
	        });

	        jLabel10.setText("Enter Lawyer’s Base Salary : ");

	        jTextField8.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField8ActionPerformed(evt);
	            }
	        });

	        jButton4.setBackground(new java.awt.Color(204, 204, 204));
	        jButton4.setForeground(new java.awt.Color(0, 0, 0));
	        jButton4.setText("Save");
	        jButton4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton4ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(41, 41, 41)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(92, 92, 92)
	                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                    .addGap(636, 636, 636)
	                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGroup(layout.createSequentialGroup()
	                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addGap(18, 18, 18)
	                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addGap(54, 54, 54)
	                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addGap(108, 108, 108)))
	                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                        .addGroup(layout.createSequentialGroup()
	                                            .addComponent(jLabel7)
	                                            .addGap(49, 49, 49)
	                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                                .addGroup(layout.createSequentialGroup()
	                                                    .addGap(0, 0, Short.MAX_VALUE)
	                                                    .addComponent(jLabel2)
	                                                    .addGap(18, 18, 18))
	                                                .addGroup(layout.createSequentialGroup()
	                                                    .addComponent(jLabel5)
	                                                    .addGap(35, 35, 35)))
	                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                                .addGroup(layout.createSequentialGroup()
	                                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                                .addGroup(layout.createSequentialGroup()
	                                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                            .addGap(42, 42, 42)))
	                                    .addGap(10, 10, 10)
	                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                    .addGap(15, 15, 15))
	                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                        .addContainerGap(1138, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel9)
	                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                        .addComponent(jButton4)
	                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                            .addGroup(layout.createSequentialGroup()
	                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                                .addComponent(jButton3))
	                                            .addGroup(layout.createSequentialGroup()
	                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                .addGap(104, 104, 104)
	                                                .addComponent(jButton2)))))
	                                .addGap(301, 301, 301))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGap(382, 382, 382)))
	                        .addGap(132, 132, 132)
	                        .addComponent(jButton1)
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(22, 22, 22)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel1)
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel6)
	                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jLabel3)
	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addComponent(jLabel4)
	                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel7)
	                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2)
	                    .addComponent(jRadioButton1)
	                    .addComponent(jRadioButton2)
	                    .addComponent(jRadioButton3))
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel5)
	                    .addComponent(jRadioButton4)
	                    .addComponent(jRadioButton5)
	                    .addComponent(jRadioButton6))
	                .addGap(35, 35, 35)
	                .addComponent(jLabel8)
	                .addGap(26, 26, 26)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton2))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel9)
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton3))
	                .addGap(31, 31, 31)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel10)
	                    .addComponent(jButton1))
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton4))
	                .addContainerGap(25, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jTextField1ActionPerformed

	    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jTextField3ActionPerformed

	    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jTextField5ActionPerformed

	    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
	 // TODO add your handling code here:
	    }//GEN-LAST:event_jRadioButton1ActionPerformed

	public void getSelected(){
	    boolean joniur = jRadioButton1.isSelected(); 
	boolean senior = jRadioButton2.isSelected();  
	boolean Partner = jRadioButton3.isSelected();
	}
	    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jRadioButton3ActionPerformed

	    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jRadioButton4ActionPerformed

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

	        String LawyerName = jTextField1.getText();
	char LawyerExperienceLevel = 0;
	if(jRadioButton1.isSelected())
	    LawyerExperienceLevel = jRadioButton1.getText().charAt(0);
	else if(jRadioButton2.isSelected())
	    LawyerExperienceLevel = jRadioButton2.getText().charAt(0);
	else if(jRadioButton3.isSelected())
	    LawyerExperienceLevel = jRadioButton3.getText().charAt(0);
	String LawyerEmailAddress = jTextField3.getText();
	String LawyerPhoneNumber = jTextField5.getText();
	char LawyerLicenseStatus = 0;
	if(jRadioButton4.isSelected())
	    LawyerLicenseStatus = jRadioButton4.getText().charAt(0);
	else if(jRadioButton5.isSelected())
	    LawyerLicenseStatus = jRadioButton5.getText().charAt(0);
	else if(jRadioButton6.isSelected())
	    LawyerLicenseStatus = jRadioButton6.getText().charAt(0);
	String LawyerBarNumber = jTextField2.getText();
	String LawyerUniversityName = jTextField4.getText();
	if(LawyerName.length()==0 || LawyerEmailAddress.length()==0 ||LawyerUniversityName.length()==0 ||LawyerBarNumber.length()==0 || LawyerPhoneNumber.length()==0)
	    JOptionPane.showMessageDialog (null, "you must fill the lawyer info");
	String CasesSize = jTextField6.getText();
	 int LawyerCasesSize = Integer.parseInt(CasesSize) ;
	String YearsOfExperience= jTextField7.getText();
	int LawyerYearsOfExperience = Integer.parseInt(YearsOfExperience) ;

	String BaseSalary = jTextField8.getText();
	double LawyerBaseSalary = Double.parseDouble(BaseSalary);
	        Lawyer NewLawyer = new Lawyer (LawyerName , LawyerExperienceLevel , LawyerEmailAddress , LawyerPhoneNumber , LawyerLicenseStatus , LawyerBarNumber , LawyerUniversityName , LawyerCasesSize , LawyerYearsOfExperience , LawyerBaseSalary );
	        LawFirm1.addLawyer(NewLawyer);
	        
	            
	                              
	         MainJframe Finish6 = new MainJframe();
	        Finish6.setVisible(true);
	        this.setVisible(false);
	       
	      
	        
	    }//GEN-LAST:event_jButton1ActionPerformed

	    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jTextField6ActionPerformed

	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	        try {
	            String MaxCases = jTextField6.getText();
	            int Max = Integer.parseInt(MaxCases) ;
	JOptionPane.showMessageDialog (null, "The Maximum Number Of cases That The Lawyer Can Handle was saved");
	        }
	        catch(NumberFormatException ex){
	            JOptionPane.showMessageDialog (null, "Error! \nPlease enter a valid number for the  Number Of Cases That The Lawyer Can Handle");
	        }
	    }//GEN-LAST:event_jButton2ActionPerformed

	    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	        
	        try {
	            String YearOfExperince = jTextField7.getText();
	            int Experince = Integer.parseInt(YearOfExperince) ;
	JOptionPane.showMessageDialog (null, "The Lawyer’s Years Of Experience was saved");
	        }
	        catch(NumberFormatException ex){
	            JOptionPane.showMessageDialog (null, "Error! \nPlease enter a valid number for the Lawyer’s Years Of Experience"); }
	    }//GEN-LAST:event_jButton3ActionPerformed

	    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jTextField8ActionPerformed

	    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
	        try {
	            String BaseSalary = jTextField8.getText();
	            int Salary = Integer.parseInt(BaseSalary) ;
	 JOptionPane.showMessageDialog (null, "The base salary was saved");
	        }
	        catch(NumberFormatException ex){
	            JOptionPane.showMessageDialog (null, "Error! \nPlease enter a valid number for the Base Salary");
	        }
	    }//GEN-LAST:event_jButton4ActionPerformed

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(HireLawyerJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(HireLawyerJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(HireLawyerJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(HireLawyerJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new HireLawyerJframe().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.ButtonGroup buttonGroup2;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JButton jButton4;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JRadioButton jRadioButton1;
	    private javax.swing.JRadioButton jRadioButton2;
	    private javax.swing.JRadioButton jRadioButton3;
	    private javax.swing.JRadioButton jRadioButton4;
	    private javax.swing.JRadioButton jRadioButton5;
	    private javax.swing.JRadioButton jRadioButton6;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    private javax.swing.JTextField jTextField5;
	    private javax.swing.JTextField jTextField6;
	    private javax.swing.JTextField jTextField7;
	    private javax.swing.JTextField jTextField8;
	    // End of variables declaration//GEN-END:variables
}
